# Generated by Django 5.2.5 on 2025-08-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('organizer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
